### ISSUE TITLE
Query not returned

### ISSUE THREAD

**Issue by samponeill** [imsamtar/hasurafire#2]
Great work though I can't get my queries to return. I'm using a gql tag and setting headers with Authorization: Bearer: accessToken

There's no error messages

Do you have a working example?

**Comment by imsamtar** [comment]
By default Query, Mutation are in pending state. You can start query by passing `started`.

You have two options.
```
<Query started query={graphql query}>
<!-- Do whatever you want -->
</Query>
```

or
```
<Query query={graphql query} let:execute>
   <button slot="pending" on:click={execute} >Query now</div>
</Query>
```
Just let me know if it works.

**Comment by samponeill** [comment]
Success! Thank you so much
